server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: microservice_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservice_logs
          env: dev
          service: microservice-auth
          __path__: /var/log/mylogs/dev/microservice-auth/*/*/*/server.log

      - targets:
          - localhost
        labels:
          job: microservice_logs
          env: prod
          service: microservice-auth
          __path__: /var/log/mylogs/prod/microservice-auth/*/*/*/server.log
